project:
  type: website

website:
  title: "Loretta Ziyue Hu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.cssqua
    toc: true

editor: visual

