project:
  type: website

website:
  title: "Loretta Ziyue Hu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: morph
    background-color: violet
    css: styles.cssqua
    toc: true

editor: visual

execute: 
  freeze: auto

